


version: "3.4"
services:
    
    mqtt:
        image: eclipse-mosquitto:latest
        container_name: mqttServer 
        ports:
            - 1883:1883
            - 9001:9001
        expose:
            - 9001
        volumes:
            - ${WORKSPACE}/mosquitto.conf:/mosquitto/config/mosquitto.conf
            - mosquitto-data:/mosquitto/data
            - mosquitto-log:/mosquitto/log
            - VIRTUAL_PORT=9001
            - VIRTUAL_HOST=mqtt.rpi.iot.at.thales
        networks:
            - backend
        restart: always

    influxdb:
        image: influxdb:latest
        container_name: influxdb
        ports:
            - 8086:8086
            - 8083:8083
        expose:
            - 8083
        volumes:
            - influxdb-data:/var/lib/influxdb
        environment:
            - VIRTUAL_HOST=influxdb.rpi.iot.at.thales
            - VIRTUAL_PORT=8083
        networks:
            - backend
        restart: always

    grafana:
        image: grafana/grafana:master
        container_name: grafana
        ports:
            - 3000:3000
        expose:
            - 3000
        environment:
            - VIRTUAL_HOST=grafana.rpi.iot.at.thales
            - VIRTUAL_PORT=3000
        networks:
            - backend
        restart: always
  
    nodered:
        image: nodered/node-red:latest
        container_name: nodered
        ports:
            - 1880:1880
        expose:
            - 1880
        environment:
            - VIRTUAL_HOST=nodered.rpi.iot.at.thales
            - VIRTUAL_PORT=1880
        networks:
            - backend
        restart: always
  
    nginx:
        image: jwilder/nginx-proxy:alpine-arm
        container_name: nginx
        ports:
            - 80:80
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro
            - ${WORKSPACE}/index.html:/www/data/index.html
            - ${WORKSPACE}/mynginx.conf:/etc/nginx/conf.d/mynginx.conf
            - ${WORKSPACE}/nginx.tmpl:/app/nginx.tmpl
        networks:
            - backend
        restart: always

volumes:
  mosquitto-data:
  mosquitto-log:
  influxdb-data:

networks:
  backend:
